language: generic
env:
  global:
    - CLI_VERSION=latest
  matrix:
    - BOARD="arduino:avr:uno"
    - BOARD="arduino:avr:mega:cpu=atmega2560"
    - BOARD="arduino:sam:arduino_due_x_dbg"
    - BOARD="arduino:samd:arduino_zero_edbg"
    - BOARD="arduino:samd:mkr1000"
    - BOARD="Intel:arc32:arduino_101"
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mkdir -p $HOME/bin
  - mv arduino-cli-*-linux64 $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - if [[ "$BOARD" =~ "arduino:avr:" ]]; then
      arduino-cli core install arduino:avr;
    fi
  - if [[ "$BOARD" =~ "arduino:sam:" ]]; then
      arduino-cli core install arduino:sam;
    fi
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino-cli core install arduino:samd;
    fi
  - if [[ "$BOARD" =~ "Intel:arc32" ]]; then
      arduino-cli core install Intel:arc32;
    fi
  - buildExampleSketch() { arduino-cli compile --verbose --warnings all --fqbn $BOARD $PWD/examples/$1; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch AP_SimpleWebServer
  - buildExampleSketch CheckWifi101FirmwareVersion
  - buildExampleSketch ConnectNoEncryption
  - buildExampleSketch ConnectWithWEP
  - buildExampleSketch ConnectWithWPA
  - if ! [[ "$BOARD" =~ "arduino:avr:" ]]; then buildExampleSketch FirmwareUpdater; fi
  - buildExampleSketch MDNS_WiFiWebServer
  - buildExampleSketch ScanNetworks
  - buildExampleSketch SimpleWebServerWiFi
  - buildExampleSketch WiFiChatServer
  - buildExampleSketch WiFiPing
  - buildExampleSketch WiFiSSLClient
  - buildExampleSketch WiFiUdpNtpClient
  - buildExampleSketch WiFiUdpSendReceiveString
  - buildExampleSketch WiFiWebClient
  - buildExampleSketch WiFiWebClientRepeating
  - buildExampleSketch WiFiWebServer

